preset: recommended
risky: true
enabled:
  - length_ordered_imports
disabled:
  - unary_operator_spaces
  - phpdoc_separation
  - phpdoc_order
  - alpha_ordered_imports
  - align_double_arrow
finder:
  exclude:
    - modules
    - node_modules
    - vendor
  name: "*.php"
